Module['FLANN_INDEX_LINEAR'] = 0;
Module['FLANN_INDEX_KDTREE'] = 1;
Module['FLANN_INDEX_KMEANS'] = 2;
Module['FLANN_INDEX_COMPOSITE'] = 3;
Module['FLANN_INDEX_KDTREE_SINGLE'] = 4;
Module['FLANN_INDEX_HIERARCHICAL'] = 5;
Module['FLANN_INDEX_LSH'] = 6;
Module['FLANN_INDEX_SAVED'] = 254;
Module['FLANN_INDEX_AUTOTUNED'] = 255;

Module['FLANN_CENTERS_RANDOM'] = 0;
Module['FLANN_CENTERS_GONZALES'] = 1;
Module['FLANN_CENTERS_KMEANSPP'] = 2;

Module['FLANN_LOG_NONE'] = 0;
Module['FLANN_LOG_FATAL'] = 1;
Module['FLANN_LOG_ERROR'] = 2;
Module['FLANN_LOG_WARN'] = 3;
Module['FLANN_LOG_INFO'] = 4;
Module['FLANN_LOG_DEBUG'] = 5;

Module['FLANN_DIST_EUCLIDEAN'] = 1;
Module['FLANN_DIST_L2'] = 1;
Module['FLANN_DIST_MANHATTAN'] = 2;
Module['FLANN_DIST_L1'] = 2;
Module['FLANN_DIST_MINKOWSKI'] = 3;
Module['FLANN_DIST_MAX'] = 4;
Module['FLANN_DIST_HIST_INTERSECT'] = 5;
Module['FLANN_DIST_HELLINGER'] = 6;
Module['FLANN_DIST_CHI_SQUARE'] = 7;
Module['FLANN_DIST_KULLBACK_LEIBLER'] = 8;
Module['FLANN_DIST_HAMMING'] = 9;
Module['FLANN_DIST_HAMMING_LUT'] = 10;
Module['FLANN_DIST_HAMMING_POPCNT'] = 11;
Module['FLANN_DIST_L2_SIMPLE'] = 12;

Module['FLANN_NONE'] = -1;
Module['FLANN_INT8'] = 0;
Module['FLANN_INT16'] = 1;
Module['FLANN_INT32'] = 2;
Module['FLANN_INT64'] = 3;
Module['FLANN_UINT8'] = 4;
Module['FLANN_UINT16'] = 5;
Module['FLANN_UINT32'] = 6;
Module['FLANN_UINT64'] = 7;
Module['FLANN_FLOAT32'] = 8;
Module['FLANN_FLOAT64'] = 9;

Module['FLANN_CHECKS_UNLIMITED'] = -1;
Module['FLANN_CHECKS_AUTOTUNED'] = -2;
